### ISSUE TITLE
Joke?

### ISSUE THREAD

**Issue by LimeBlast** [iamale/awesome-nocode#1]
I can't tell, is this a joke? (i.e. there are no awesome nocode platforms), or did the list simply never get started?

**Comment by notpushkin** [comment]
It is indeed :) At the time I made this repo, nocode itself [was just a joke](https://github.com/kelseyhightower/nocode) (or perhaps the “real” #nocode was a thing already – just that I didn't hear of it at the time).

A real nocode/lowcode Awesome list would be a nice idea, but right now there are very, very few nocode things that are both user-friendly and privacy-friendly (which is a really important aspect in my opinion!) so I think I'll pass.

**Comment by LimeBlast** [comment]
In that case, I approve of your humour :)
